Technical Documents/Source/website/logins/urls.py
from django.urls import path, include
from django.contrib.auth.urls import views as auth_views

from . import views

app_name = 'logins'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
]

Technical Documents/Source/website/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('quiz/', views.quiz, name='quiz'),
    path('resources/', views.resources, name='resources'),
    path('settings/', views.settings, name='settings'),
    path('store/', views.store, name='store'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
]

Technical Documents/Source/website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('logins.urls')),
    path('admin/', admin.site.urls),
    path('bin/', include('bin.urls')),
    path('home/', include('main.urls')),
    path('quiz/', include('event.urls')),
    path('store/', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Technical Documents/Source/website/logins/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from event.models import Trash, Event
from bin.models import Bin
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

class PlayerGroup(Group):
    """Group authentication allowing player actions
    WARNING NOT IMPLEMENTED"""
    name = 'players'
    permissions = []

    def __str__(self):
        return self.name

class Player(models.Model):
    """Player user profile bound to one and only one User instance."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='player')
    points = models.IntegerField(default=0)
    storeItems = models.ManyToManyField('store.StoreItem')
    memberSince = models.DateTimeField(auto_now_add=True)
    attempted_events = models.ManyToManyField(Event, related_name='players_attempted')

    def __str__(self):
        return self.user.__str__()

    def add_trash_item(self, trash_item):
        bin_item, created = self.bin.binitemthrough_set.get_or_create(trash=trash_item)
        bin_item.amount += 1
        bin_item.save()

    def add_points(self, points):
        self.points += points
        self.save()

@receiver(post_save, sender=Player)
def create_bin(sender, instance, created, **kwargs):
    if created:
        Bin.objects.create(player=instance)

Technical Documents/Source/website/logins/views.py
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import loader
from django.template.loader import get_template
from django.urls import reverse
from logins.models import Player
from django import forms
from django.contrib.auth import logout
from django.template.loader import get_template
from django.shortcuts import redirect
from leaderboard.models import Leaderboard


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

def index(request):
    return render(request, 'logins/index.html')

def user_login(request):
    # Initialize error message
    error_message = ''
    # If HTTP request method is POST
    if request.method == 'POST':
        # Initialize form object with POST data
        form = AuthenticationForm(data=request.POST)
        # If form is valid
        if form.is_valid():
            # Get cleaned data from form
            # data = form.cleaned_data
            # Authenticate user with provided credentials
            user = form.get_user()
            # If user is authenticated
            if user is not None:
                # Log in user
                login(request, user)
                # Redirect user to home page
                return HttpResponseRedirect(reverse('home'))
        # If form is not valid
        else:
            # Reinitialize form with POST data
            form = AuthenticationForm(request.POST)
            # Set error message
            error_message = 'Invalid username or password'
    # If HTTP request method is not POST
    else:
        # Initialize form object
        form = AuthenticationForm()
    # Load login template
    template = loader.get_template('logins/login.html')
    # Render template with form and error message
    return HttpResponse(template.render({'form': form.as_p(), 'error_message': error_message}, request))


def register(request):
    # Initialize error message
    error_message = ''
    # If HTTP request method is POST
    if request.method == 'POST':
        # Initialize form object with POST data
        form = CustomUserCreationForm(request.POST)
        # If form is valid
        if form.is_valid():
            # Get cleaned data from form
            data = form.cleaned_data
            # Extract username, email and password from data
            username = data.get('username')
            email = data.get('email')
            password = data.get('password1')
            # If user with given username doesn't already exist
            if not User.objects.filter(username=username).exists():
                # Create new user
                user = User.objects.create_user(username=username, email=email, password=password)
                # Create new player profile
                player = Player(user=user)
                # Save the Player object
                player.save()
                # Create new leaderboard instance for the player
                Leaderboard.objects.create(player=user)
                # Authenticate and log in user
                user = authenticate(request, username=username, password=password)
                login(request, user)
                # Redirect user to account page
                return HttpResponseRedirect(reverse('home'))
            # If user with given username already exists
            else:
                error_message = 'A user with that username already exists'
        # If form is not valid
        else:
            # If username already exists
            if form.has_error('username', code='unique'):
                error_message = 'This username is already taken. Please choose another one.'
            # If password fields do not match
            elif form.has_error('password1', code='password_mismatch'):
                error_message = 'The two password fields did not match. Please try again.'
            # If password is too short
            elif form.has_error('password1', code='min_length'):
                error_message = 'The password is too short. Please enter a password with at least 8 characters.'
            # If other validation errors occur
            else:
                try:
                    form.full_clean()
                except ValidationError as e:
                    error_message = e.message
    # If HTTP request method is not POST
    else:
        # Initialize form object
        form = CustomUserCreationForm()

    # Render register template
    return render(request, 'logins/register.html', {'form': form, 'error_message': error_message})

Technical Documents/Source/website/logins/templates/logins/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Outfit&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.cdnfonts.com/css/circular-std" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'logins/style.css' %}">
    
    <title>Trash to Treasure: Exeter Edition</title>
    {% csrf_token %}
</head>

<body>

    <nav class="navbar navbar-light" id="nav"><img src="../../../media/images/logo_transparentbackground.png" height="50px" width="50px"></nav>

    {% block content %}
    

    {% endblock %}
    
</body>
</html>

Technical Documents/Source/website/logins/templates/logins/base_loggedin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.cdnfonts.com/css/circular-std" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'logins/style.css' %}">
    
    <title>Trash to Treasure: Exeter Edition</title>
    {% csrf_token %}
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light mr-auto" id="nav">
        <!-- Logo -->
        <img src="../../../media/images/logo_transparentbackground.png" height="32px" width="32px">
        
        <!-- Display username -->
        <p style="text-decoration: none; color: white; font-size: 18px;" id="username">@{{ request.user.username }}</p>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

Technical Documents/Source/website/logins/templates/logins/base_loggedin_back.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.cdnfonts.com/css/circular-std" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'logins/style.css' %}">
    
    <title>Trash to Treasure: Exeter Edition</title>
    {% csrf_token %}
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light mr-auto" id="nav">
        <!-- Back button -->
        <a style="text-decoration: none; color: white; font-size: 18px;" href="javascript:history.back()">Back</a>
        
        <!-- Display username -->
        <p style="text-decoration: none; color: white; font-size: 18px;" id="username">@{{ request.user.username }}</p>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

Technical Documents/Source/website/logins/templates/logins/bin_item.html
{% extends 'logins/base_loggedin_back.html' %}

{% block content %}

<div class="container-fluid">


    <div class="row form">

        <!-- buffer col -->
        <div class="col-sm-2 col-md-4 col-lg-4"></div>

            <!-- content column -->
        <div class="col-sm-8 col-md-4 col-lg-4 form">


            <div class="row align-items-center bin_item_row">
                    <div class="col-0"></div>
                    <div class="col-12">
                        <div class="img_details">
                            <h2>25</h2>
                            <img src="../../media/images/trash_icons/water-bottle.png" height="200px" width="200px"><br><br>
                            <h2>Bottle</h2><br>
                            <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                            <br>
                        </div>
                    </div>
                    <div class="col-0"></div>
            </div>
 
        </div>

        <!-- buffer col -->
        <div class="col-sm-2 col-md-4 col-lg-4"></div>
    </div>

</div>


    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!--
        <script src="bootstrap-5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    -->
    <!--<script src="bootstrap5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>-->
</body>
</html>

{% endblock %}

Technical Documents/Source/website/logins/templates/logins/index.html
{% extends 'logins/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row login_title">
            <div class="col-md-12 col-lg-12 text">
                <h3>Trash 2 Treasure:<br>Exeter Edition</h3>
            </div>
        </div>

        <div class="row form">
            <!-- buffer col -->
            <div class="col-sm-3 col-md-4 col-lg-4"></div>

            <!-- content column -->
            <div class="col-sm-6 col-md-4 col-lg-4 form">
                <form method="post">
                    <div class="row btns_row">
                        <div class="col-lg-12 btns_col" style="text-align: center;">
                            <a class="action-btn" href="{% url 'logins:login' %}"><p style="margin: auto;">Login</p></a><br><br>
                            <p>or</p>
                            <a class="action-btn" href="{% url 'logins:register' %}"><p style="margin: auto;">Register</p></a>
                        </div>
                    </div>
                </form>
            </div>
            <!-- buffer col -->
            <div class="col-sm-3 col-md-4 col-lg-4"></div>
        </div>
        <script>

        </script>
    </div>
{% endblock %}

Technical Documents/Source/website/logins/templates/logins/login.html
{% extends 'logins/base.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row login_title">
        <div class="col-md-12 col-lg-12 text">
            <h3>Login portal</h3>
        </div>
    </div>

    <div class="row form">

        <!-- buffer col -->
        <div class="col-sm-3 col-md-4 col-lg-4"></div>

            <!-- content column -->
            <div class="col-sm-6 col-md-4 col-lg-4 form" style="text-align: center;">

                <form action="{% url 'logins:login' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <row class="row btns_row">

                        <div class="col-lg-12 btns_col">

                            <a href=""><button type="submit" value="submit" class="btn btn-primary">Login</button></a>

                        </div>

                    </row>
                </form>
            </div>

        <!-- buffer col -->
        <div class="col-sm-3 col-md-4 col-lg-4"></div>
    </div>
    <p style="text-align: center" class="error">{{error_message}}</p>
</div>


    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!--
        <script src="bootstrap-5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    -->
    <!--<script src="bootstrap5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>-->
</body>
</html>

{% endblock %}

Technical Documents/Source/website/logins/templates/logins/map.html
{% extends 'logins/base_loggedin.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row form">

        <!-- buffer col -->
        <div class="col-sm-2 col-md-4 col-lg-4"></div>

            <!-- content column -->
            <div class="col-sm-8 col-md-4 col-lg-4" style="text-align: center;">

                <div id="map"></div>



            </div>

        <!-- buffer col -->
        <div class="col-sm-2 col-md-4 col-lg-4"></div>
    </div>

</div>


    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOi7xS0UARD-TETo1z6L6qpw2q8_PBeqg&callback=initMap&v=weekly" defer></script>

      <script>
        // Initialize and add the map
// Initialize and add the map
// Initialize and add the map
function initMap() {
  // The location of Uluru 50.73552987384898, -3.534578186423475
  const exeter = { lat: 50.735529873, lng: -3.5345781864 };
  // The map, centered at Uluru
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 15,
    center: exeter,
  });
  // The marker, positioned at Uluru
  const marker = new google.maps.Marker({
    position: exeter,
    map: map,
  });
}

window.initMap = initMap;
      </script>
    <!--
        <script src="bootstrap-5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    -->
    <!--<script src="bootstrap5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>-->
</body>
</html>

{% endblock %}

Technical Documents/Source/website/logins/templates/logins/register.html
{% extends 'logins/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row login_title">
            <div class="col-md-12 col-lg-12 text">
                <h3>Register</h3>
            </div>
        </div>

        <div class="row form">
            <!-- buffer col -->
            <div class="col-sm-3 col-md-4 col-lg-4"></div>

            <!-- content column -->
            <div class="col-sm-6 col-md-4 col-lg-4 form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Username</label>
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter username"><br>
                    </div>

                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email"><br>
                    </div>

                    <div class="form-group">
                        <label for="id_password1">Password</label>
                        <input type="password" class="form-control" id="id_password1" name="password1" placeholder="Enter password"><br>
                    </div>

                    <div class="form-group">
                        <label for="id_password2">Confirm password</label>
                        <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Confirm password"><br>
                    </div>

                    <div class="row btns_row">
                        <div class="col-lg-12 btns_col">
                            <button type="submit" class="btn btn-primary">Create Account</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- buffer col -->
            <div class="col-sm-3 col-md-4 col-lg-4"></div>
        </div>
    </div>
{% endblock %}